name: CI - base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  code-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up golang
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Vet
      run: make vet

    - name: Run unit tests
      run: make unit-tests
